<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2015.1.0.342
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Opinia zgłoszenie',
	'heading' => 'Przesłano nowy formularz',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Zaznaczone',
		'checkbox_unchecked' => 'Niezaznaczone',
		'submitted_from' => 'Formularz wysłany z witryny:%s',
		'submitted_by' => 'Adres IP gościa:%s',
		'too_many_submissions' => 'Z tego IP przesłano ostatnio zbyt wiele zgłoszeń',
		'failed_to_send_email' => 'Nie udało się wysłać wiadomości e-mail',
		'invalid_reCAPTCHA_private_key' => 'Nieprawidłowy klucz prywatny reCAPTCHA.',
		'invalid_field_type' => 'Nieznany typ pola „%s”.',
		'invalid_form_config' => 'Pole „%s” ma nieprawidłową konfigurację.',
		'unknown_method' => 'Nieznana metoda żądania serwera'
	),
	'email' => array(
		'from' => 'panda.support@interia.pl',
		'to' => 'panda.support@interia.pl'
	),
	'fields' => array(
		'custom_U852' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Nazwa',
			'required' => true,
			'errors' => array(
				'required' => 'Pole „Nazwa” jest wymagane.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'E-mail',
			'required' => true,
			'errors' => array(
				'required' => 'Pole „E-mail” jest wymagane.',
				'format' => 'Adres e-mail znajdujący się w polu „E-mail” jest nieprawidłowy.'
			)
		),
		'custom_U848' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Wiadomość',
			'required' => false,
			'errors' => array(
			)
		)
	)
);

process_form($form);
?>
